/* Generated By:JavaCC: Do not edit this line. simplejavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface simplejavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int CLASS = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int FALSE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULTIPLY = 22;
  /** RegularExpression Id. */
  int DIVIDE = 23;
  /** RegularExpression Id. */
  int LEFTBRACKET = 24;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 25;
  /** RegularExpression Id. */
  int LEFTBRACE = 26;
  /** RegularExpression Id. */
  int RIGHTBRACE = 27;
  /** RegularExpression Id. */
  int LEFTPARENTHESIS = 28;
  /** RegularExpression Id. */
  int RIGHTPARENTHESIS = 29;
  /** RegularExpression Id. */
  int PERIOD = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int EQUAL = 32;
  /** RegularExpression Id. */
  int NOTEQUAL = 33;
  /** RegularExpression Id. */
  int LESSTHAN = 34;
  /** RegularExpression Id. */
  int GREATERTHAN = 35;
  /** RegularExpression Id. */
  int LESSTHANOREQUAL = 36;
  /** RegularExpression Id. */
  int GREATERTHANOREQUAL = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int INCREMENT = 41;
  /** RegularExpression Id. */
  int DECREMENT = 42;
  /** RegularExpression Id. */
  int PLUS = 43;
  /** RegularExpression Id. */
  int SEMICOLON = 44;
  /** RegularExpression Id. */
  int GETS = 45;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 4>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"else\"",
    "\"for\"",
    "\"class\"",
    "\"do\"",
    "\"false\"",
    "\"if\"",
    "\"true\"",
    "\"while\"",
    "\"return\"",
    "\"new\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\";\"",
    "\"=\"",
  };

}
